# Generated by Django 5.1.4 on 2025-01-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0004_remove_viewingactivity_title_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingactivity',
            name='title_id',
            field=models.ForeignKey(db_column='title_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped_app.titles'),
        ),
    ]
