# Generated by Django 5.1.4 on 2025-01-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0008_alter_titles_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewingactivity',
            name='title_id',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
