# Generated by Django 5.1.4 on 2025-01-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0009_remove_viewingactivity_title_id_delete_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_type', models.CharField(blank=True, choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'titles',
                'managed': True,
            },
        ),
    ]
