# Generated by Django 5.1.5 on 2025-01-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0012_genres_titles_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genres',
            old_name='name',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_id',
            field=models.IntegerField(unique=True),
        ),
    ]
