# Generated by Django 5.1.5 on 2025-01-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0014_remove_genres_id_alter_genres_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
    ]
