# Generated by Django 5.1.4 on 2025-01-10 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewingactivity',
            options={'managed': True},
        ),
    ]
