# Generated by Django 5.1.4 on 2025-01-11 03:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0002_alter_viewingactivity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingactivity',
            name='title_id',
            field=models.ForeignKey(db_column='title_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped_app.titles'),
        ),
        migrations.AlterField(
            model_name='viewingactivity',
            name='device_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viewingactivity',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='viewingactivity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
