# Generated by Django 5.1.4 on 2025-01-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0005_viewingactivity_title_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'managed': True},
        ),
    ]
