# Generated by Django 5.1.4 on 2025-01-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0006_alter_titles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='video_type',
            field=models.CharField(blank=True, choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='title_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
