# Generated by Django 5.1.4 on 2025-01-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0007_titles_video_type_alter_titles_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='title_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
