# Generated by Django 5.1.5 on 2025-01-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0011_viewingactivity_title_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('genre_id', models.IntegerField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'genres',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='wrapped_app.genres'),
        ),
    ]
