# Generated by Django 5.1.5 on 2025-01-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0013_rename_name_genres_genre_alter_genres_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='id',
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
