# Generated by Django 5.1.5 on 2025-01-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0015_remove_titles_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(default=None, related_name='titles', to='wrapped_app.genres'),
        ),
    ]
