# Generated by Django 5.1.5 on 2025-02-18 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0016_titles_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingData',
            fields=[
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('duration', models.TimeField(default=datetime.time(0, 0))),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_type', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_bookmark', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'viewing_data',
                'managed': True,
            },
        ),
    ]
