# Generated by Django 5.1.5 on 2025-02-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0017_viewingdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewingdata',
            old_name='video_type',
            new_name='device_type',
        ),
    ]
