# Generated by Django 5.1.5 on 2025-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0018_rename_video_type_viewingdata_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
