# Generated by Django 5.1.5 on 2025-02-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0019_alter_titles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'title_data',
                'managed': True,
            },
        ),
    ]
