# Generated by Django 5.1.5 on 2025-02-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0019_alter_titles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingdata',
            name='title_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped_app.titles'),
        ),
    ]
