# Generated by Django 5.1.5 on 2025-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0020_titledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledata',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
