# Generated by Django 5.1.5 on 2025-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0021_titledata_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledata',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
