# Generated by Django 5.1.5 on 2025-03-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0022_titledata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titledata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
