# Generated by Django 5.1.5 on 2025-03-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0023_alter_titledata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titledata',
            old_name='id',
            new_name='title_id',
        ),
    ]
