# Generated by Django 5.1.5 on 2025-03-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0024_rename_id_titledata_title_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingdata',
            name='title_id',
            field=models.ForeignKey(blank=True, db_column='title_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped_app.titledata'),
        ),
    ]
